language: node_js
notifications:
  email: false
node_js:
  - "4.2"
deploy:
  provider: heroku
  api_key:
    secure: "26f01ce9-f060-47ec-b7f3-cb1a58438559"
before_script:
  - npm install
  - sudo apt-get install -y tree
  - bower i
script:
  - gulp build
  - tree build